apiVersion: apps/v1
kind: Deployment
metadata:
  name: se
  namespace: boramae
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: my-webserver
      labels:
        app: webserver
    spec:
      containers:
      - name: my-webserver
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  ports:
  - name: web-port
    port: 8080
    targetPort: 80
    #nodePort: 31000
    nodePort: 31500
  selector:
    app: webserver
  type: NodePort
